name: starveto_app
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - flask
  - python-dotenv
  - flask-sqlalchemy
  - flask-migrate
  - flask-wtf
  - wtforms
  - email-validator
  - nltk==3.9.1
  - anaconda::beautifulsoup4
  - conda-forge::selenium
  - ipykernel
